name: flutter_link_previewer
description: >
  URL preview extracted from the provided text with
  basic customization and ability to render from cached data.
version: 3.0.0
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_link_previewer

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.4.1
  flutter_linkify: ^5.0.2
  html: ^0.15.0
  http: ^0.13.4
  linkify: ^4.1.0
  meta: ^1.7.0
  url_launcher: ^6.1.3

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
