name: flutter_link_previewer
description: >
  Preview of the link extracted from the provided text
  with basic customization and ability to render from cached data.
version: 1.0.3
homepage: https://github.com/flyerhq/flutter_link_previewer

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_chat_types: ^2.0.5
  flutter_linkify: ^5.0.0
  html: ^0.15.0
  http: ^0.13.1
  linkify: ^4.0.0
  meta: ^1.3.0
  url_launcher: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
