name: flutter_link_previewer
description: >
  URL preview extracted from the provided text with
  basic customization and ability to render from cached data.
version: 2.6.0
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_link_previewer

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.2.0
  flutter_linkify: ^5.0.2
  html: ^0.15.0
  http: ^0.13.4
  linkify: ^4.1.0
  meta: ^1.3.0
  url_launcher: ^6.0.12

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
