name: flutter_link_previewer
description: >
  URL preview extracted from the provided text with
  basic customization and ability to render from cached data.
version: 2.0.1
homepage: https://github.com/flyerhq/flutter_link_previewer

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_chat_types: ^2.1.2
  flutter_linkify: ^5.0.2
  html: ^0.15.0
  http: ^0.13.3
  linkify: ^4.0.0
  meta: ^1.3.0
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
